force-app/main/default/objects/ConnectionMessage2__e/ConnectionMessage2__e.object-meta.xml
<CustomObject>
    <label>ConnectionMessage2</label>
    <pluralLabel>ConnectionMessage2</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConnectionMessage2__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConnectionMessage2__e/fields/MsgType__c.field-meta.xml
<CustomField>
    <fullName>MsgType__c</fullName>
    <label>MsgType</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectionMessage2__e/fields/receivedId__c.field-meta.xml
<CustomField>
    <fullName>receivedId__c</fullName>
    <label>receivedId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConnectionMessage2__e/fields/senderId__c.field-meta.xml
<CustomField>
    <fullName>senderId__c</fullName>
    <label>senderId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VideoCallingController.cls
public with sharing class VideoCallingController {
    @AuraEnabled(cacheable=true)
    public static List<User> getUserData(String userId){
        List<User> userList=new List<User>();
        try {
             userList=[SELECT Id, FirstName, LastName FROM User where Id !=:userId];
            return userList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static void sendmessage(String message,string sendby,String type,String receiveId){
        ConnectionMessage2__e event = new ConnectionMessage2__e(Message__c = message,senderId__c=sendby,MsgType__c=type,receivedId__c=receiveId);
         Database.SaveResult result = EventBus.publish(event);
       System.debug(result);
     }
}